var queries = {
	hospitals:[
				"SELECT * FROM hospitals",
				"SELECT COUNT(*) as Total_Number_Of_Hospitals FROM hospitals",
				"SELECT COUNT(*) as Number_of_Hospitals, Field_of_Spec from hospitals GROUP BY Field_of_Spec",
				"SELECT * FROM hospitals WHERE Field_of_Spec='MILITARY'",
				"SELECT * FROM hospitals ORDER BY Capacity DESC",
				"SELECT * FROM hospitals WHERE Capacity>50",
				"SELECT * FROM hospitals WHERE Capacity<50",
				"SELECT * FROM hospitals WHERE (Latitude>40 and Latitude<50) and (Longitude>40 and Longitude<50)",
				"SELECT SUM(Capacity) as Total_Capcity FROM hospitals",
				"SELECT Name FROM hospitals WHERE Latitude = (SELECT MAX(Latitude) FROM hospitals)",
				"SELECT Name FROM hospitals WHERE Latitude = (SELECT MIN(Latitude) FROM hospitals)",
				"SELECT Name FROM hospitals WHERE Latitude = (SELECT MIN(Longitude) FROM hospitals)",
				"SELECT Name FROM hospitals WHERE Latitude = (SELECT MAX(Longitude) FROM hospitals)",
				"SELECT Name, MAX(Capacity) FROM hospitals",
				"SELECT Name, MIN(Capacity) FROM hospitals"],
	doctors:[
				"SELECT * FROM doctors",
				"SELECT COUNT(*) AS Number_Of_Doctors FROM doctors",
				"SELECT hospitals.Name, COUNT(*) as Number_Of_Doctors from doctors, hospitals where doctors.Hospital_Id=hospitals.Unique_Id GROUP BY Hospital_Id",
				"SELECT * FROM doctors WHERE Years_of_Exp>10",
				"SELECT * FROM doctors WHERE Years_of_Exp<10",
				"SELECT Field_of_Spec, COUNT(*) as Number_of_Doctors FROM doctors GROUP BY Field_of_Spec",
				"SELECT Field_of_Spec, MAX(Number_of_Doctors) AS Max_Number_of_Doctors FROM (SELECT Field_of_Spec, COUNT(*) AS Number_of_Doctors FROM doctors GROUP BY Field_of_Spec) as Count_Spec_Table",
				"SELECT * FROM doctors WHERE Years_of_Exp=(SELECT MAX(Years_of_Exp) FROM doctors)",
				"SELECT * FROM doctors WHERE Years_of_Exp=(SELECT MIN(Years_of_Exp) FROM doctors)",
				"SELECT * FROM doctors ORDER BY Years_of_Exp ASC",
				"SELECT AVG(Years_of_Exp) FROM doctors"],
	patients:[
				"SELECT * FROM patients",
				"SELECT COUNT(*) AS Number_of_Patients FROM patients",
				"SELECT * FROM patients WHERE Gender='M'",
				"SELECT * FROM patients WHERE Gender='F'",
				"SELECT COUNT(patients.Name), doctors.Name FROM doctors, patients WHERE patients.Doctor_Id=doctors.Id GROUP BY doctors.name",
				"SELECT COUNT(*) FROM patients WHERE Illness=’Cancer’",
				"SELECT Illness, COUNT(*) FROM patients GROUP BY Illness",
				"SELECT COUNT(DISTINCT(Blood_Group)) FROM patients",
				"SELECT Blood_Group, COUNT(*) FROM patients GROUP BY Blood_Group",
				"SELECT Blood_Group, MAX(cnt) AS mx FROM (SELECT Blood_Group, COUNT(*) as cnt FROM patients GROUP BY Blood_Group) as p",
				"SELECT Blood_Group, MIN(cnt) AS mn FROM (SELECT Blood_Group, COUNT(*) as cnt FROM patients GROUP BY Blood_Group) as p",
				"SELECT Medication_Drug, COUNT(*) FROM patients GROUP BY Medication_Drug",
				"SELECT Medication_Drug, MAX(cnt) AS max_drug FROM (SELECT Medication_Drug, COUNT(*) as cnt FROM patients GROUP BY Medication_Drug) as p",
				"SELECT COUNT(*) FROM patients WHERE Age>50",
				"SELECT AVG(Age) FROM patients",
				"SELECT MAX(Age) FROM patient",
				"SELECT Illness, MAX(cnt) AS max_illness FROM (SELECT Illness, COUNT(*) as cnt FROM patients GROUP BY Illness) as p",
				"SELECT MAX(Age) FROM patients WHERE Illness=‘Cancer’",
				"SELECT MIN(Age) FROM patients WHERE Illness=‘Cancer’",
				"SELECT AVG(Age) FROM patients WHERE Illness=‘Cancer’",
				"SELECT DISTINCT(Medication_Drug) FROM patients WHERE Illness='Cancer'",
				"SELECT AVG(Weight) FROM patients",
				"SELECT MAX(Weight) FROM patients",
				"SELECT MIN(Weight) FROM patients",
				"SELECT Name, MAX(Height) FROM patients",
				"SELECT Name, MIN(Height) FROM patients",
				"SELECT (*) FROM patients WHERE Name LIKE ‘A%’"
				],
	blood_bank:[		
				"SELECT * FROM blood_bank",
				"SELECT COUNT(*) AS Number_Of_Blood_Banks FROM blood_bank",
				"SELECT COUNT(DISTINCT(Donors)) FROM blood_bank",
				"SELECT AVG(Quantity) FROM blood_bank",
				"SELECT Blood_Group, MAX(cnt) AS max_bg FROM (SELECT Blood_Group, COUNT(*) as cnt FROM blood_bank GROUP BY Blood_Group) as p",
				"SELECT Donors, MAX(Quantity) FROM blood_bank",
				"SELECT Donors,MIN(Quantity) FROM blood_bank",
				"SELECT Recipents, MAX(Quantity) FROM blood_bank",
				"SELECT Recipents,MIN(Quantity) FROM blood_bank",
				"SELECT * FROM blood_bank ORDER BY Quantity DESC",
				"SELECT Blood_Group, SUM(Quantity) FROM blood_bank GROUP BY Blood_Group"
				],
	pharmacy_products:[	
				"SELECT * FROM pharmacy_products",
				"SELECT COUNT(*) AS Number_Of_Pharmacy_Products FROM pharmacy_products",
				"SELECT COUNT(*) FROM pharmacy_products",
				"SELECT COUNT(*) FROM pharmacy_products WHERE Name_of_Drug > 'A' and Name_of_Drug < 'B'"
				]
}
module.exports  = queries