import pandas as pd
import numpy as np
from random import randint as ran
blood = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']

names = ["OLIVIA","RUBY","EMILY","GRACE","JESSICA","CHLOE","SOPHIE","LILY","AMELIA","EVIE","MIA","ELLA","CHARLOTTE","LUCY","MEGAN","ELLIE","ISABELLE","ISABELLA","HANNAH","KATIE","AVA","HOLLY","SUMMER","MILLIE","DAISY","PHOEBE","FREYA","ABIGAIL","POPPY","ERIN","EMMA","MOLLY","IMOGEN","AMY","JASMINE","ISLA","SCARLETT","LEAH","SOPHIA","ELIZABETH","EVA","BROOKE","MATILDA","CAITLIN","KEIRA","ALICE","LOLA","LILLY","AMBER","ISABEL","LAUREN","GEORGIA","GRACIE","ELEANOR","BETHANY","MADISON","AMELIE","ISOBEL","PAIGE","LACEY","SIENNA","LIBBY","MAISIE","ANNA","REBECCA","ROSIE","TIA","LAYLA","MAYA","NIAMH","ZARA","SARAH","LEXI","MADDISON","ALISHA","SOFIA","SKYE","NICOLE","LEXIE","FAITH","MARTHA","HARRIET","ZOE","EVE","JULIA","AIMEE","HOLLIE","LYDIA","EVELYN","ALEXANDRA","MARIA","FRANCESCA","TILLY","FLORENCE","ALICIA","ABBIE","EMILIA","COURTNEY","MARYAM","ESME","JACK","OLIVER","THOMAS","HARRY","JOSHUA","ALFIE","CHARLIE","DANIEL","JAMES","WILLIAM","SAMUEL","GEORGE","JOSEPH","LEWIS","ETHAN","MOHAMMED","DYLAN","BENJAMIN","ALEXANDER","JACOB","RYAN","LIAM","JAKE","MAX","LUKE","TYLER","CALLUM","MATTHEW","JAYDEN","OSCAR","ARCHIE","ADAM","RILEY","HARVEY","HARRISON","LUCAS","MUHAMMAD","HENRY","ISAAC","LEO","CONNOR","EDWARD","FINLEY","LOGAN","NOAH","CAMERON","ALEX","OWEN","RHYS","NATHAN","JAMIE","MICHAEL","MASON","TOBY","AARON","CHARLES","BEN","THEO","LOUIS","FREDDIE","FINLAY","LEON","HARLEY","DAVID","MOHAMMAD","REECE","KIAN","KAI","KYLE","BRANDON","HAYDEN","ZACHARY","KIERAN","LUCA","ASHTON","BAILEY","SEBASTIAN","GABRIEL","SAM","EVAN","BRADLEY","ELLIOT","JOHN","TAYLOR","JOE","COREY","REUBEN","JOEL","ROBERT","ELLIS","BLAKE","AIDAN","LOUIE","CHRISTOPHER","EWAN","JAY","MORGAN","BILLY","SEAN","ZAK"]
i=0
while(i<1000):
    df2 = pd.DataFrame({'RECEIPTANTS': names[np.random.randint(0,199)],
                    'DONORS': names[np.random.randint(0,199)],
                    'BLOOD_GP': blood[np.random.randint(0,7)],
                    'QUANTITY': str(np.random.randint(0,100))}, index=[i])
    df2.to_csv("blood_bank.csv", sep=',', encoding='utf-8', mode='a', header=False)
    i = i+1

